In [ ]:
CPU :- Central Processing Unit
GPU :- Graphical Processing Unit
TPU :- Tensor Processing Unit

In [1]:
import numpy as np

In [2]:
arr = np.array([23,45,12,67,34])

In [3]:
print(arr)

[23 45 12 67 34]


In [4]:
arr

array([23, 45, 12, 67, 34])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([23,45,12,67,34,70.13])

In [7]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 70.13])

In [15]:
arr1 = np.array([23,45,12,67,34,'st'])

In [11]:
arr1

array(['23', '45', '12', '67', '34', 'st'], dtype='<U11')

In [ ]:
#dtype = unicode is less than 11

In [12]:
arr1[2]

'12'

In [16]:
%%timeit
arr1 = np.array([23,45,12,67,34,'st'])

3.57 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
arr.ndim # To check the dimension of array

1

In [20]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(5,7.5,10)

array([5.])

In [24]:
arr(range(23,2.5,-1))

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
#arange accept the float value range can't accept float

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
# 2d array

In [41]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [42]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr2.shape

(4, 3)

In [44]:
arr2.size

12

In [45]:
arr2.ndim

2

In [46]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr2.shape

(4, 3)

In [49]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [51]:
arr2.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [58]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [59]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [60]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [69]:
arr2[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr2[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr

array(['23', '45', '12', '67', '34', 'st'], dtype='<U11')

In [72]:
arr = np.array([1,2,3,1,4,2,6,2,2])

In [73]:
np.unique(arr)

array([1, 2, 3, 4, 6])

In [81]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
np.linalg.inv(arr3)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [83]:
arr2 @ arr3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])